### ISSUE TITLE
Where is the data of CDR1, CDR2 and CDR2.5?

### ISSUE THREAD

**Issue by JinChengneng** [emmijokinen/TCRGP#2]
Hi there! Thanks a lot for your efforts to ```TCRGP```, which is really helpful in TCR affinity prediction.
I've noticed that ```TCRGP``` can use entire CDR chains to predict by letting ```cdr_types=[['cdr3','cdr1','cdr2','cdr25'],['cdr3','cdr1','cdr2','cdr25']]```. However, there are no columns named 'cdr1','cdr2' or 'cdr25' in the csv files in the  ```training_data``` folder.
I would appreciate it if you could help figure out where is the data of CDR1, CDR2 and CDR2.5. Thank you very much!

**Comment by emmijokinen** [comment]
Hi @JinChengneng! And sorry for not noticing your message earlier. If you want to utilize also other CDRs in addition to CDR3, only the V-gene and allele (e.g. TRBV10-1*01) are needed. TCRGP can deduce the corresponding CDR1, CDR2 and CDR2.5 regions based on that. This is done simply by looking up the correct sequences from data/alphabeta_db.tsv, which has been constructed following the IMGT definitions. The files in the training_data folder have columns for Vb- and Va-genes when they have been available.
